name: flutter_list
description: A new Flutter project.
version: 1.1.0+3


environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  json_annotation: ^2.0.0
  http: ^0.12.0+2
  provider: ^3.0.0+1
  shared_preferences: ^0.5.7+3
  expandable: ^3.0.1
  logger: ^0.7.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^2.0.0
  build_runner: ^1.0.0
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/locale/en.json
    - assets/locale/ko.json

  fonts:
      - family: SF-Pro-Text-Regular
        fonts:
          - asset: assets/SF-Pro-Text-Regular.otf

      - family: SF-Pro-Text-Bold
        fonts:
          - asset: assets/SF-Pro-Text-Bold.otf

      - family: Calibre-Semibold
        fonts:
          - asset: assets/Calibre Semibold.otf
      - family: Goyang-L
        fonts:
          - asset: assets/goyang_L.ttf
      - family: Goyang-R
        fonts:
          - asset: assets/goyang_R.ttf

